#### Sudoku

In [1]:
import numpy as np

In [2]:
grid = [[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,8,9,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,0,8],
        [0,0,0,4,1,9,0,0,5],
        [0,0,0,0,8,0,0,7,9]]

In [3]:
print(grid)

[[5, 3, 0, 0, 7, 0, 0, 0, 0], [6, 0, 0, 1, 9, 5, 0, 0, 0], [0, 8, 9, 0, 0, 0, 0, 6, 0], [8, 0, 0, 0, 6, 0, 0, 0, 3], [4, 0, 0, 8, 0, 3, 0, 0, 1], [7, 0, 0, 0, 2, 0, 0, 0, 6], [0, 6, 0, 0, 0, 0, 2, 0, 8], [0, 0, 0, 4, 1, 9, 0, 0, 5], [0, 0, 0, 0, 8, 0, 0, 7, 9]]


In [4]:
print(np.matrix(grid))

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 8 9 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 0 8]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


In [5]:
# check for position
# check for each square (3x3)

def possible(y,x,n):
    global grid
    for i in range(0,9):
        if grid[y][i] == n:
            return False
    for i in range(0,9):
        if grid[i][x] == n:
            return False
    y0 = (y//3)*3
    x0 = (x//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if grid[y0+i][x0+j] == n:
                return False
    return True

In [7]:
possible(4,4,3)

False

In [8]:
possible(4,4,5)

True

In [9]:
def solver():
    global grid
    for y in range(0,9):
        for x in range(0,9):
            if grid[y][x] == 0:
                for i in range(1,10):
                    if possible(y,x,i):
                        grid[y][x] = i
                        solver()
                        #backtracking
                        grid[y][x] = 0
                return
    print(np.matrix(grid))
    input("Find another solution:")

In [10]:
solver()

[[5 3 2 6 7 8 1 9 4]
 [6 4 7 1 9 5 3 8 2]
 [1 8 9 3 4 2 5 6 7]
 [8 2 1 7 6 4 9 5 3]
 [4 9 6 8 5 3 7 2 1]
 [7 5 3 9 2 1 8 4 6]
 [9 6 4 5 3 7 2 1 8]
 [2 7 8 4 1 9 6 3 5]
 [3 1 5 2 8 6 4 7 9]]
Find another solution:no
[[5 3 2 6 7 8 1 9 4]
 [6 4 7 1 9 5 3 8 2]
 [1 8 9 3 4 2 5 6 7]
 [8 2 5 7 6 1 9 4 3]
 [4 9 6 8 5 3 7 2 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 4 5 3 7 2 1 8]
 [2 7 8 4 1 9 6 3 5]
 [3 5 1 2 8 6 4 7 9]]
Find another solution:
[[5 3 2 6 7 8 9 1 4]
 [6 4 7 1 9 5 3 8 2]
 [1 8 9 3 4 2 5 6 7]
 [8 2 5 7 6 1 4 9 3]
 [4 9 6 8 5 3 7 2 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 4 8]
 [2 7 8 4 1 9 6 3 5]
 [3 5 4 2 8 6 1 7 9]]
Find another solution:
[[5 3 2 6 7 8 9 1 4]
 [6 4 7 1 9 5 3 8 2]
 [1 8 9 3 4 2 5 6 7]
 [8 9 5 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 4 8]
 [2 7 8 4 1 9 6 3 5]
 [3 5 4 2 8 6 1 7 9]]
Find another solution:
[[5 3 4 6 7 8 9 1 2]
 [6 2 7 1 9 5 3 8 4]
 [1 8 9 3 4 2 5 6 7]
 [8 5 2 7 6 1 4 9 3]
 [4 9 6 8 5 3 7 2 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 4 8]

In [ ]:
grid = [[12,11,23],[23,34,35],[51,55,56]]

In [ ]:
print(np.matrix(grid))

In [ ]:
for i in range(0,3):
    for j in range(0,3):
        print(grid[i][j])

In [ ]:
for i in range(0,3):
    for j in range(0,3):
        if grid[i][j] == 23:
            print("true", i, j)
        print("not exists", i, j)

In [20]:
def isFirstBigger(num1,num2): 
    if num1 > num2: 
        return True 
    return False 

In [21]:
isFirstBigger(3,2)

True

In [28]:
x = 8
(x//3)*3

6