##  Sudoku - sample possible

In [19]:
grid = [[0,7,0,0,2,0,0,4,6],
        [0,6,0,0,0,0,8,9,0],
        [2,0,0,8,0,0,7,1,5],
        [0,8,4,0,9,7,0,0,0],
        [7,1,0,0,0,0,0,5,9],
        [0,0,0,1,3,0,4,8,0],
        [6,9,7,0,0,2,0,0,8],
        [0,5,8,0,0,0,0,6,0],
        [4,3,0,0,8,0,0,7,0]]

In [20]:
def possible(y,x,n):
    global grid
    for i in range(0,9):
        if grid[y][i] == n:
            return False
    for i in range(0,9):
        if grid[i][x] == n:
            return False
    x0 = (x//3)*3
    y0 = (y//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if grid[y0+i][x0+i] == n:
                return False
    return True

In [3]:
possible(8,1,2)

True

In [6]:
x = 9
x0 = (x//3)*3
print(x0)

9


In [7]:
def possible2(y,x,n):
    global grid
    for i in range(0,9):
        if grid[y][i] == n:
            print("y: ", y)
            print("i: ",i)
            print("False1")
            return False
    for i in range(0,9):
        if grid[i][x] == n:
            print(i)
            print("x: ", x)
            print("False2")
            return False
    x0 = (x//3)*3
    y0 = (y//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if grid[y0+i][x0+i] == n:
                print("False3")
                return False
    print("True")
    return True

In [8]:
possible2(4,4,1)

y:  4
i:  1
False1


False

# The Real game

In [21]:
import numpy as np

In [22]:
grid = [[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,8,9,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,0,8],
        [0,0,0,4,1,9,0,0,5],
        [0,0,0,0,8,0,0,7,9]]

In [23]:
print(grid)

[[5, 3, 0, 0, 7, 0, 0, 0, 0], [6, 0, 0, 1, 9, 5, 0, 0, 0], [0, 8, 9, 0, 0, 0, 0, 6, 0], [8, 0, 0, 0, 6, 0, 0, 0, 3], [4, 0, 0, 8, 0, 3, 0, 0, 1], [7, 0, 0, 0, 2, 0, 0, 0, 6], [0, 6, 0, 0, 0, 0, 2, 0, 8], [0, 0, 0, 4, 1, 9, 0, 0, 5], [0, 0, 0, 0, 8, 0, 0, 7, 9]]


In [24]:
print(np.matrix(grid))

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 8 9 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 0 8]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


In [25]:
# check for position
# check for each square (3x3)

def possible(y,x,n):
    global grid
    for i in range(0,9):
        if grid[y][i] == n:
            return False
    for i in range(0,9):
        if grid[i][x] == n:
            return False
    y0 = (y//3)*3
    x0 = (x//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if grid[y0+i][x0+j] == n:
                return False
    return True

In [15]:
possible(4,4,3)

False

In [16]:
possible(4,4,5)

True

In [26]:
def solver():
    global grid
    for y in range(0,9):
        for x in range(0,9):
            if grid[y][x] == 0:
                for i in range(1,10):
                    if possible(y,x,i):
                        grid[y][x] = i
                        solver()
                        #backtracking
                        grid[y][x] = 0
                return
    print(np.matrix(grid))
    input("Find another solution:")

In [27]:
solver()

[[5 3 2 6 7 8 1 9 4]
 [6 4 7 1 9 5 3 8 2]
 [1 8 9 3 4 2 5 6 7]
 [8 2 1 7 6 4 9 5 3]
 [4 9 6 8 5 3 7 2 1]
 [7 5 3 9 2 1 8 4 6]
 [9 6 4 5 3 7 2 1 8]
 [2 7 8 4 1 9 6 3 5]
 [3 1 5 2 8 6 4 7 9]]


Find another solution: 


[[5 3 2 6 7 8 1 9 4]
 [6 4 7 1 9 5 3 8 2]
 [1 8 9 3 4 2 5 6 7]
 [8 2 5 7 6 1 9 4 3]
 [4 9 6 8 5 3 7 2 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 4 5 3 7 2 1 8]
 [2 7 8 4 1 9 6 3 5]
 [3 5 1 2 8 6 4 7 9]]


Find another solution: 


[[5 3 2 6 7 8 9 1 4]
 [6 4 7 1 9 5 3 8 2]
 [1 8 9 3 4 2 5 6 7]
 [8 2 5 7 6 1 4 9 3]
 [4 9 6 8 5 3 7 2 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 4 8]
 [2 7 8 4 1 9 6 3 5]
 [3 5 4 2 8 6 1 7 9]]


Find another solution: 


[[5 3 2 6 7 8 9 1 4]
 [6 4 7 1 9 5 3 8 2]
 [1 8 9 3 4 2 5 6 7]
 [8 9 5 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 4 8]
 [2 7 8 4 1 9 6 3 5]
 [3 5 4 2 8 6 1 7 9]]


Find another solution: 


[[5 3 4 6 7 8 9 1 2]
 [6 2 7 1 9 5 3 8 4]
 [1 8 9 3 4 2 5 6 7]
 [8 5 2 7 6 1 4 9 3]
 [4 9 6 8 5 3 7 2 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 4 8]
 [2 7 8 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


Find another solution: 
